"""Script to convert a directory of Python files or notebook into a single file."""

import argparse
import pathlib

import nbformat

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("directory")
args = parser.parse_args()
directory = pathlib.Path(args.directory)

if not directory.is_dir():
    exit()

python_files = sorted(directory.glob("**/*.py"))
notebook_files = sorted(directory.glob("**/*.ipynb"))


def extract_notebook_code(path: pathlib.Path) -> str:
    try:
        with open(path) as fp:
            notebook = nbformat.read(fp, nbformat.NO_CONVERT)
        cells = notebook["cells"]
        code_cells = [c for c in cells if c["cell_type"] == "code"]
        content = "\n\n".join([cell["source"] for cell in code_cells])
        return content
    except Exception:
        return "# ERROR LOADING JSON"


output_file = directory.with_suffix(".py")
if output_file.exists():
    raise FileExistsError(f"Output file {output_file} already exists.")

output_file.write_text(
    f"### AUTOGENERATED BY CONCATENING FILES FROM {directory.name} submission"
)

with open(output_file, "a") as f:
    for file in python_files + notebook_files:
        content = (
            file.read_text()
            if file.name.endswith(".py")
            else extract_notebook_code(file)
        )
        f.write(f"""

# File {file.name}

""")
        f.write(content)
        f.write("""


""")
